# Generated by Django 2.1.7 on 2019-03-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdb',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='title',
            field=models.CharField(default='标题', max_length=50),
        ),
    ]
